### ISSUE TITLE
Not show the new bar

### ISSUE THREAD

**Issue by wildcatquebec** [SkinnyDevi/webui_tavernai_charas#1]
Hello i tried to install Webui_Tarvernai_Charas
But it not look to work.

i tried with 2 method

1-Install manually
2-Install with the Install extension in the session with the git url.

i see the new extension available but i cannot see any new options.

OS: Ubuntu 22.04
WebUI (One click installer) ; Lastest
CPU : i9-10900F 2.80Ghz
GPU 0: Nvidia 4070TI
GPU 1: Nvidia 3080

![Screenshot from 2023-08-15 21-55-34](https://github.com/SkinnyDevi/webui_tavernai_charas/assets/46546296/bc360ee4-24d0-4754-83ed-1f73de342727)

Can somebody can help with this thx :)

**Comment by SkinnyDevi** [comment]
Hi! Thank you for your feedback. 

Have you seen the instructions of oobabooga on how to use extensions not builtin?

If not:
You must go inside the `webui.py` file, and under CMD_ARGS you must add:
`--extensions `webui_tabernai_charas`

Add this, then restart your WebUI. You will have to do this with any other extension you install.

**Comment by wildcatquebec** [comment]
Thx alot webui.py refer to CMD_FLAGS.txt lol i just add --extensions webui_tabernai_charas in CMD_FLAGS.txt and it work :) Thx alot

**Comment by SkinnyDevi** [comment]
No problem!
