### ISSUE TITLE
If this extension is enabled, restarting the webui will freeze without any response.

### ISSUE THREAD

**Issue by lisea2017** [SkinnyDevi/webui_tavernai_charas#10]
If this extension is enabled, restarting the webui will freeze without any response. What is the problem?

**Comment by SkinnyDevi** [comment]
HI! Thank you for the issue. Could you elaborate a bit further? What exactly were you doing to restart? Loading a new extension and restarting or simply restarting using the restart button in settings?

Also, do you have the flag `--extensions webui_tavernai_charas` in your `CMD_FLAGS.txt` file?

**Comment by Gamefriend996** [comment]
Have an similar problem. Say's at the end "extensions\\webui_tavernai_chars\\temp" path not found.
![Screenshot 2024-03-05 105653](https://github.com/SkinnyDevi/webui_tavernai_charas/assets/161429705/977efcfe-e47a-471e-b794-23afdefcbfc8)

**Comment by SkinnyDevi** [comment]
I see the problem. I will try to fix this when i get home and report back. Thank you!

**Comment by SkinnyDevi** [comment]
Hello! The extension has now been fixed. Please update the extension!

**Comment by lisea2017** [comment]
> HI! Thank you for the issue. Could you elaborate a bit further? What exactly were you doing to restart? Loading a new extension and restarting or simply restarting using the restart button in settings?
> 
> Also, do you have the flag `--extensions webui_tavernai_charas` in your `CMD_FLAGS.txt` file?


Yes, I added --extensions webui_tavernai_charas to CMD_FLAGS.txt, then launched the web UI, and it got stuck there for a long time without any response.

**Comment by lisea2017** [comment]
ok.

> > HI! Thank you for the issue. Could you elaborate a bit further? What exactly were you doing to restart? Loading a new extension and restarting or simply restarting using the restart button in settings?
> > Also, do you have the flag `--extensions webui_tavernai_charas` in your `CMD_FLAGS.txt` file?
> 
> Yes, I added --extensions webui_tavernai_charas to CMD_FLAGS.txt, then launched the web UI, and it got stuck there for a long time without any response.

After I updated the code, it can work normally now. Thank you
