### ISSUE TITLE
Bug: Error fetching Previous/Next page in search

### ISSUE THREAD

**Issue by przewodo** [SkinnyDevi/webui_tavernai_charas#14]
When you are on the search tab and click next section, this error occour:

extensions\webui_tavernai_charas\ui\featured.py", line 193, in next_category_section
    current_val = int(current.get("label")) + 1

AttributeError: 'str' object has no attribute 'get'

1. Go on the Search Tab
2. Click on Next Section or Previous Section
4. See error on the console.

**Comment by SkinnyDevi** [comment]
> When you are on the search tab and click next section, this error occour:
> 
> 
> 
> extensions\webui_tavernai_charas\ui\featured.py", line 193, in next_category_section
> 
>     current_val = int(current.get("label")) + 1
> 
> 
> 
> AttributeError: 'str' object has no attribute 'get'
> 
> 
> 
> Steps to reproduce the behavior:
> 
> 1. Go on the Search Tab
> 
> 2. Click on Next Section or Previous Section
> 
> 4. See error on the console.

Hi, sorry for the late response. I'll look into it in the upcoming days. Thank you.

**Comment by SkinnyDevi** [comment]
Hello! The fix has been deployed. Please update the extension. Thank you for the report!

**Comment by przewodo** [comment]
> Hello! The fix has been deployed. Please update the extension. Thank you for the report!

No problem! I thank you for you awesome plugin and work.
