### ISSUE TITLE
Bug: Issue Name

### ISSUE THREAD

**Issue by MODOMison** [SkinnyDevi/webui_tavernai_charas#15]
**Describe the bug**
GPT says
The error you're encountering, SSLCertVerificationError, is occurring because the SSL certificate for tavernai.net has expired. When the SSL certificate is expired, the web client cannot verify the server's identity, and thus, refuses to establish a secure connection.

Here’s what you can do to potentially resolve the issue:

Update the Certificate: If you control the server tavernai.net, you should update the SSL certificate to a valid one. If you don't control it, contact the server admin and inform them about the expired certificate.

**Steps To Reproduce**
install with URL into extensions zone

**Additional context**
works in removefolder

mass error message:

16:19:08-337892 INFO     Starting Text generation web UI
16:19:08-340847 WARNING
                         You are potentially exposing the web UI to the entire internet without any access password.
                         You can create one with the "--gradio-auth" flag like this:

                         --gradio-auth username:password

                         Make sure to replace username:password with your own.
16:19:08-343839 INFO     Loading the extension "webui_tavernai_charas"
16:19:08-435875 INFO     Loading the extension "openai"
16:19:08-545138 INFO     OpenAI-compatible API URL:

                         http://0.0.0.0:5000

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connectionpool.py:466 in _make_request                                                                        │
│                                                                                                                      │
│    465             try:                                                                                              │
│ ❱  466                 self._validate_conn(conn)                                                                     │
│    467             except (SocketTimeout, BaseSSLError) as e:                                                        │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connectionpool.py:1095 in _validate_conn                                                                      │
│                                                                                                                      │
│   1094         if conn.is_closed:                                                                                    │
│ ❱ 1095             conn.connect()                                                                                    │
│   1096                                                                                                               │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connection.py:652 in connect                                                                                  │
│                                                                                                                      │
│   651                                                                                                                │
│ ❱ 652         sock_and_verified = _ssl_wrap_socket_and_match_hostname(                                               │
│   653             sock=sock,                                                                                         │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connection.py:805 in _ssl_wrap_socket_and_match_hostname                                                      │
│                                                                                                                      │
│   804                                                                                                                │
│ ❱ 805     ssl_sock = ssl_wrap_socket(                                                                                │
│   806         sock=sock,                                                                                             │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\util\ssl_.py:465 in ssl_wrap_socket                                                                           │
│                                                                                                                      │
│   464                                                                                                                │
│ ❱ 465     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)                               │
│   466     return ssl_sock                                                                                            │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\util\ssl_.py:509 in _ssl_wrap_socket_impl                                                                     │
│                                                                                                                      │
│   508                                                                                                                │
│ ❱ 509     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)                                      │
│   510                                                                                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\ssl.py:517 in   │
│ wrap_socket                                                                                                          │
│                                                                                                                      │
│    516         # ctx._wrap_socket()                                                                                  │
│ ❱  517         return self.sslsocket_class._create(                                                                  │
│    518             sock=sock,                                                                                        │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\ssl.py:1104 in  │
│ _create                                                                                                              │
│                                                                                                                      │
│   1103                         raise ValueError("do_handshake_on_connect should not be specifie                      │
│ ❱ 1104                     self.do_handshake()                                                                       │
│   1105         except:                                                                                               │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\ssl.py:1382 in  │
│ do_handshake                                                                                                         │
│                                                                                                                      │
│   1381                 self.settimeout(None)                                                                         │
│ ❱ 1382             self._sslobj.do_handshake()                                                                       │
│   1383         finally:                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired
(_ssl.c:1006)

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connectionpool.py:789 in urlopen                                                                              │
│                                                                                                                      │
│    788             # Make the request on the HTTPConnection object                                                   │
│ ❱  789             response = self._make_request(                                                                    │
│    790                 conn,                                                                                         │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connectionpool.py:490 in _make_request                                                                        │
│                                                                                                                      │
│    489                 new_e = _wrap_proxy_error(new_e, conn.proxy.scheme)                                           │
│ ❱  490             raise new_e                                                                                       │
│    491                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)

The above exception was the direct cause of the following exception:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\r │
│ equests\adapters.py:667 in send                                                                                      │
│                                                                                                                      │
│   666         try:                                                                                                   │
│ ❱ 667             resp = conn.urlopen(                                                                               │
│   668                 method=request.method,                                                                         │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\connectionpool.py:843 in urlopen                                                                              │
│                                                                                                                      │
│    842                                                                                                               │
│ ❱  843             retries = retries.increment(                                                                      │
│    844                 method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]                           │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\u │
│ rllib3\util\retry.py:519 in increment                                                                                │
│                                                                                                                      │
│   518             reason = error or ResponseError(cause)                                                             │
│ ❱ 519             raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type                       │
│   520                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
MaxRetryError: HTTPSConnectionPool(host='tavernai.net', port=443): Max retries exceeded with url:
/api/categories/$recent/characters?nsfw=on (Caused by SSLError(SSLCertVerificationError(1, '[SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\server.py:271 in <module>               │
│                                                                                                                      │
│   270         # Launch the web UI                                                                                    │
│ ❱ 271         create_interface()                                                                                     │
│   272         while True:                                                                                            │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\server.py:165 in create_interface       │
│                                                                                                                      │
│   164                                                                                                                │
│ ❱ 165         extensions_module.create_extensions_tabs()  # Extensions tabs                                          │
│   166         extensions_module.create_extensions_block()  # Extensions block                                        │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\modules\extensions.py:207 in            │
│ create_extensions_tabs                                                                                               │
│                                                                                                                      │
│   206             with gr.Tab(display_name, elem_classes="extension-tab"):                                           │
│ ❱ 207                 extension.ui()                                                                                 │
│   208                                                                                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\extensions\webui_tavernai_charas\script │
│ .py:29 in ui                                                                                                         │
│                                                                                                                      │
│   28 def ui():                                                                                                       │
│ ❱ 29     charas_ui.mount_ui()                                                                                        │
│   30                                                                                                                 │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\extensions\webui_tavernai_charas\ui\mai │
│ n.py:23 in mount_ui                                                                                                  │
│                                                                                                                      │
│   22         with gr.TabItem("Online Characters"):                                                                   │
│ ❱ 23             featured_ui()                                                                                       │
│   24                                                                                                                 │
│                                                                                                                      │
│                                               ... 5 frames hidden ...                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\r │
│ equests\api.py:73 in get                                                                                             │
│                                                                                                                      │
│    72                                                                                                                │
│ ❱  73     return request("get", url, params=params, **kwargs)                                                        │
│    74                                                                                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\r │
│ equests\api.py:59 in request                                                                                         │
│                                                                                                                      │
│    58     with sessions.Session() as session:                                                                        │
│ ❱  59         return session.request(method=method, url=url, **kwargs)                                               │
│    60                                                                                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\r │
│ equests\sessions.py:589 in request                                                                                   │
│                                                                                                                      │
│   588         send_kwargs.update(settings)                                                                           │
│ ❱ 589         resp = self.send(prep, **send_kwargs)                                                                  │
│   590                                                                                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\r │
│ equests\sessions.py:703 in send                                                                                      │
│                                                                                                                      │
│   702         # Send the request                                                                                     │
│ ❱ 703         r = adapter.send(request, **kwargs)                                                                    │
│   704                                                                                                                │
│                                                                                                                      │
│ C:\Users\matto\Desktop\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\r │
│ equests\adapters.py:698 in send                                                                                      │
│                                                                                                                      │
│   697                 # This branch is for urllib3 v1.22 and later.                                                  │
│ ❱ 698                 raise SSLError(e, request=request)                                                             │
│   699                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
SSLError: HTTPSConnectionPool(host='tavernai.net', port=443): Max retries exceeded with url:
/api/categories/$recent/characters?nsfw=on (Caused by SSLError(SSLCertVerificationError(1, '[SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)')))
Press any key to continue . . .

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by SkinnyDevi** [comment]
Hello, very sorry for the late reply.

This issue (TavernAI server errors) was encountered a few months ago. It appears to be on TavernAI's side, where there servers stopped responding, and so did this extension. Since this extension depends on their servers, it will not work.

If you encounter this issue again, make sure to check first at [https://tavernai.net/](https://tavernai.net/) and check if you can access the website. If you cannot access the website, their servers are not working, and a **fix is to temporarily disable this extension until their servers work again**.

If their servers work, and you keep getting this error, please re-open this issue. Thank you!
