### ISSUE TITLE
Character card view before download?

### ISSUE THREAD

**Issue by mykeehu** [SkinnyDevi/webui_tavernai_charas#2]
I like the extension! What I miss is that I can't view the character map before downloading, but just click on the image to start the download. I read that there are API limitations, so I would suggest that when I click on the character, the character card should appear (popup or drop down below) and there should be a Download button at the bottom/top of it.

Another idea: could the categories be sorted alphabetically somehow?

**Comment by SkinnyDevi** [comment]
Hi! Thank you for your feedback!

When you say you can't view the character map before downloading, are you suggesting an implementation such as a dialog to alert (confirm, cancel) before downloading? Or something like a separate interface that shows you the character's name, description and extra information before downloading?

Categories can indeed be sorted alphabetically. I'll add that to the next batch of updates.

**Comment by mykeehu** [comment]
> Or something like a separate interface that shows you the character's name, description and extra information before downloading?

That's exactly what I meant. So I click on the card, and the character sheet comes up, where I can read what it contains, and then download it if I want.

**Comment by RandomLegend** [comment]
Yeah i'd like to see what the card is actually about before downloading it aswell.

As of right now i have to browse the cards on a different site to read about them. Then search for them to download insidei the webui

**Comment by SkinnyDevi** [comment]
Great news!

As of now, the extension has been updated. To update, just reinstall the extension using this github's link as you would normally do for installing a new extension.

Images and a changelog have been added to the readme. Thank you for the suggestion!

**Comment by mykeehu** [comment]
Fantastic news, great thanks for developing and new features!
