### ISSUE TITLE
Feature: Card Previewer Mini-Gallery

### ISSUE THREAD

**Issue by TheInvisibleMage** [SkinnyDevi/webui_tavernai_charas#7]
**Problem/Use Case**
I typically swap between several character cards when looking at their previews, to compare them, grab ideas for prompts from each, etc. However, this process requires me to repeatedly navigate to/from the Online Previewer, even if I want to see a character again that I've already previewed.

**Potential Solution**
A mini "gallery" below the currently-previewed character's image, displaying smaller images of the most recently previewed characters. The user would be able to click these to load their data from temp storage, effectively giving a far quicker way to preview any characters they have already looked at.

**Alternatives**
Another option could be to combine the Online Characters and Card Preview tabs, by placing the Previewer on the right side of the screen. However, this could result in a very crowded UI experience.

**Comment by SkinnyDevi** [comment]
Thank you for the suggestion! This has now been implemented in the latest update (1.3.0).
