### ISSUE TITLE
Bug: Search Crash

### ISSUE THREAD

**Issue by drago87** [SkinnyDevi/webui_tavernai_charas#9]
**Describe the bug**
Going below Sction 1 in the search tab looks the whole interface

**Steps To Reproduce**
1. Go to 'Search'
2. Make sure 'Current section is = 1'
3. Click on 'Previous section'

Error
No error but the whole interface stopps working untill reloading the tab

**Comment by SkinnyDevi** [comment]
Hi! This issue has been resolved and will be applied in the next update.
